# Generated by Django 2.1.1 on 2021-05-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('bitbucket', 'BitBucket')], max_length=20)),
                ('status', models.CharField(choices=[('up-to-date', 'Up-To-Date'), ('syncing', 'Syncing')], max_length=20)),
            ],
        ),
    ]
