# Generated by Django 2.1.1 on 2021-05-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
