# Generated by Django 2.1.1 on 2021-05-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='commits.Repository')),
            ],
        ),
    ]
